name: Feature request
description: Suggest an improvement or new feature.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Share the problem first, then your proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user or business problem are we solving?
      placeholder: Describe the current pain point.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the expected behavior and scope.
      placeholder: Describe your preferred solution.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Optional alternatives or trade-offs.

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: What must be true for this to be considered done?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-check
      options:
        - label: I searched for duplicate feature requests
          required: true
